### ISSUE TITLE
railwayでの実行に失敗する

### ISSUE THREAD

**Issue by kengokawamura** [tsuemura/fastify-webapp-sample#6]
```
{"statusCode":500,"code":"42P01","error":"Internal Server Error","message":"relation \"session\" does not exist"}
```

ReadMeに従いrailwayで生成されたドメインにアクセスしたところ上記エラーとなります。

db:migrateが実行されていないためと推測しています。

READMEに従って実行しているのですが、追加の手順等あればご教示ください。

**Comment by tsuemura** [comment]
@kengokawamura 
ご迷惑をおかけしてすみません。こちら、Railway側の仕様変更で、build中に外部ネットワークを使わない設定になったため、マイグレーションが通らないようです。
以下サポートサイト内に回避方法を記載しておりますので、お試しいただけますでしょうか？

https://github.com/tsuemura/practical-guide-for-test-automation-support?tab=readme-ov-file#%E9%87%8D%E8%A6%81railway%E3%81%B8%E3%81%AE%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4%E6%99%82%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A62024-08-07

こちらのリポジトリのReadmeについては追って更新しておきます。

**Comment by kengokawamura** [comment]
@tsuemura 

ご教示いただいた回避方法で無事マイグレーションを通すことができました。
ありがとうございます。
また、サポートサイトの見落とし失礼いたしました。

ご確認いただきありがとうございました 🙇

**Comment by tsuemura** [comment]
@kengokawamura 無事解決したとのことで何よりです！また何かございましたらお気軽にご質問ください 👍
